package pl.pszczepanski.techut.zad02.service;


import pl.pszczepanski.techut.zad02.domain.Shoe;

import java.sql.*;

public class ShoeService {
    private final String URL = "jdbc:hsqldb:hsql://localhost/workdb";
    private final Connection connection;
    private final Statement statement;
    private final String CREATE_TABLE_SQL = "CREATE TABLE Shoe (id bigint GENERATED BY DEFAULT AS IDENTITY, producer VARCHAR(30), type VARCHAR(30), size INT,  productionDate DATE, price DOUBLE)";
    private boolean tableExists = false;

    public ShoeService() throws SQLException {
        connection = DriverManager.getConnection(URL);
        statement = connection.createStatement();

        ResultSet rs = connection.getMetaData().getTables(null, null, null, null);

        while (rs.next()) {
            if ("Shoe".equalsIgnoreCase(rs.getString("table_name"))) {
                tableExists = true;

                break;
            }
        }

        if (!tableExists) {
            statement.executeUpdate(CREATE_TABLE_SQL);
        }
    }

    public void addShoe(Shoe shoe) throws SQLException {
        String addShoe = "INSERT INTO Shoe(producer, type, size, productionDate, price) VALUES('" + shoe.getProducer() + "', '" + shoe.getType() + "', '" + shoe.getSize() + "', '" +shoe.getProductionDate() + "', '" + shoe.getPrice() + "')";

        statement.executeUpdate(addShoe);
    }

    public void showAllShoes() throws SQLException {
        String allShoes = "SELECT * FROM Shoe";

        ResultSet rs = statement.executeQuery(allShoes);

        while (rs.next()) {
            System.out.println("Producer: " + rs.getString("producer") + "\nType: " + rs.getString("type") + "\nSize: " + rs.getInt("size") +"\nProduction date: " + rs.getDate("productionDate") + "\nPrice: " + rs.getDouble("price")  + "\n");
        }
    }

    public void removeShoes() throws SQLException {
        String removeShoes = "DELETE FROM Shoe";

        statement.executeQuery(removeShoes);
    }
}
